[package]
name = "workers"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "workers-bin"
path = "src/main.rs"

[dependencies]
axum = "0.8.6"
tokio = { version = "1.47.1", features = ["full"] }
